package nl.tudelft.inpoint;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.net.wifi.WifiManager;
import android.widget.TextView;

import java.util.HashMap;

public class Globals {
    public static TextView selectedRoom;
    public static int mapDefaultColor;
    public static int mapSelectedColor;
    public static boolean recording = false;
    public static final String DATABASE_NAME = "InPoint.sqlite";
    public static volatile HashMap<String, int[]> rssValues = new HashMap<>();
    public static WifiManager wifiManager;
    public static SQLiteHelper db;

    public static int getColor(int i) {
        if (i == 0) return R.color.mapDefault;
        if (i == 1) return R.color.color1;
        if (i == 2) return R.color.color2;
        if (i == 3) return R.color.color3;
        if (i == 4) return R.color.color4;
        if (i == 5) return R.color.color5;
        if (i == 6) return R.color.color6;
        if (i == 7) return R.color.color7;
        if (i == 8) return R.color.color8;
        if (i == 9) return R.color.color9;
        if (i == 10) return R.color.color10;
        if (i == 11) return R.color.color11;
        if (i == 12) return R.color.color12;
        if (i == 13) return R.color.color13;
        if (i == 14) return R.color.color14;
        if (i == 15) return R.color.color15;
        if (i == 16) return R.color.color16;
        if (i == 17) return R.color.color17;
        if (i == 18) return R.color.color18;
        if (i == 19) return R.color.color19;
        if (i == 20) return R.color.color20;
        if (i == 21) return R.color.color21;
        if (i == 22) return R.color.color22;
        if (i == 23) return R.color.color23;
        if (i == 24) return R.color.color24;
        if (i == 25) return R.color.color25;
        if (i == 26) return R.color.color26;
        if (i == 27) return R.color.color27;
        if (i == 28) return R.color.color28;
        if (i == 29) return R.color.color29;
        if (i == 30) return R.color.color30;
        if (i == 31) return R.color.color31;
        if (i == 32) return R.color.color32;
        if (i == 33) return R.color.color33;
        if (i == 34) return R.color.color34;
        if (i == 35) return R.color.color35;
        if (i == 36) return R.color.color36;
        if (i == 37) return R.color.color37;
        if (i == 38) return R.color.color38;
        if (i == 39) return R.color.color39;
        if (i == 40) return R.color.color40;
        if (i == 41) return R.color.color41;
        if (i == 42) return R.color.color42;
        if (i == 43) return R.color.color43;
        if (i == 44) return R.color.color44;
        if (i == 45) return R.color.color45;
        if (i == 46) return R.color.color46;
        if (i == 47) return R.color.color47;
        if (i == 48) return R.color.color48;
        if (i == 49) return R.color.color49;
        if (i == 50) return R.color.color50;
        if (i == 51) return R.color.color51;
        if (i == 52) return R.color.color52;
        if (i == 53) return R.color.color53;
        if (i == 54) return R.color.color54;
        if (i == 55) return R.color.color55;
        if (i == 56) return R.color.color56;
        if (i == 57) return R.color.color57;
        if (i == 58) return R.color.color58;
        if (i == 59) return R.color.color59;
        if (i == 60) return R.color.color60;
        if (i == 61) return R.color.color61;
        if (i == 62) return R.color.color62;
        if (i == 63) return R.color.color63;
        if (i == 64) return R.color.color64;
        if (i == 65) return R.color.color65;
        if (i == 66) return R.color.color66;
        if (i == 67) return R.color.color67;
        if (i == 68) return R.color.color68;
        if (i == 69) return R.color.color69;
        if (i == 70) return R.color.color70;
        if (i == 71) return R.color.color71;
        if (i == 72) return R.color.color72;
        if (i == 73) return R.color.color73;
        if (i == 74) return R.color.color74;
        if (i == 75) return R.color.color75;
        if (i == 76) return R.color.color76;
        if (i == 77) return R.color.color77;
        if (i == 78) return R.color.color78;
        if (i == 79) return R.color.color79;
        if (i == 80) return R.color.color80;
        if (i == 81) return R.color.color81;
        if (i == 82) return R.color.color82;
        if (i == 83) return R.color.color83;
        if (i == 84) return R.color.color84;
        if (i == 85) return R.color.color85;
        if (i == 86) return R.color.color86;
        if (i == 87) return R.color.color87;
        if (i == 88) return R.color.color88;
        if (i == 89) return R.color.color89;
        if (i == 90) return R.color.color90;
        if (i == 91) return R.color.color91;
        if (i == 92) return R.color.color92;
        if (i == 93) return R.color.color93;
        if (i == 94) return R.color.color94;
        if (i == 95) return R.color.color95;
        if (i == 96) return R.color.color96;
        if (i == 97) return R.color.color97;
        if (i == 98) return R.color.color98;
        if (i == 99) return R.color.color99;
        if (i == 100) return R.color.color100;
        return R.color.mapDefault;
    }
}
